-- Initial schema for SeeMyCity, extracted from the live database (2026-07-07).
-- Requires PostgreSQL with the PostGIS extension available.

CREATE EXTENSION IF NOT EXISTS postgis;

-- Keeps updated_at current on any row update.
CREATE FUNCTION public.trigger_set_timestamp() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$;

-- Static details for South African municipalities (seeded from Municipal
-- Demarcation Board + StatsSA data; see database/ backup for a full seed).
CREATE TABLE public.municipalities (
    id character varying NOT NULL,
    name text NOT NULL,
    province text NOT NULL,
    population real,
    classification text,
    address text,
    website text,
    phone text,
    district_id character varying,
    district_name text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT municipalities_pkey PRIMARY KEY (id)
);
COMMENT ON TABLE public.municipalities IS 'Stores static details for South African municipalities.';

-- Geographic boundaries (GeoJSON imported via GDAL/ogr2ogr).
CREATE TABLE public.municipal_geometries (
    ogc_fid integer GENERATED BY DEFAULT AS IDENTITY,
    geom public.geometry(Geometry,4326),
    munic_id character varying NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT municipal_geometries_pkey PRIMARY KEY (ogc_fid),
    CONSTRAINT municipal_geometries_munic_id_fkey FOREIGN KEY (munic_id)
        REFERENCES public.municipalities(id) ON DELETE CASCADE
);
COMMENT ON TABLE public.municipal_geometries IS 'Stores geographic boundaries for South African municipalities.';

CREATE INDEX idx_municipal_geometries_munic_id ON public.municipal_geometries USING btree (munic_id);
CREATE INDEX municipal_geometries_geom_geom_idx ON public.municipal_geometries USING gist (geom);

-- Read-through cache of Treasury "Municipal Money" figures plus computed
-- scores, one row per municipality per financial year. An all-NULL metrics row
-- is a negative-cache marker ("upstream has no data for this year").
CREATE TABLE public.financial_data (
    id uuid NOT NULL,
    municipality_id character varying NOT NULL,
    year integer NOT NULL,
    revenue numeric,
    operational_expenditure numeric,
    capital_expenditure numeric,
    debt numeric,
    audit_outcome text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    overall_score numeric(5,2),
    financial_health_score numeric(5,2),
    infrastructure_score numeric(5,2),
    efficiency_score numeric(5,2),
    accountability_score numeric(5,2),
    CONSTRAINT financial_data_pkey PRIMARY KEY (id),
    CONSTRAINT financial_data_municipality_id_year_key UNIQUE (municipality_id, year),
    CONSTRAINT financial_data_municipalities_fk FOREIGN KEY (municipality_id)
        REFERENCES public.municipalities(id)
);
COMMENT ON TABLE public.financial_data IS 'Stores cached financial metrics and calculated scores for municipalities, linked by municipality_id and year.';

CREATE INDEX financial_data_municipality_id_year_idx ON public.financial_data USING btree (municipality_id, year);

CREATE TRIGGER set_timestamp_municipalities BEFORE UPDATE ON public.municipalities
    FOR EACH ROW EXECUTE FUNCTION public.trigger_set_timestamp();
CREATE TRIGGER set_timestamp_municipal_geometries BEFORE UPDATE ON public.municipal_geometries
    FOR EACH ROW EXECUTE FUNCTION public.trigger_set_timestamp();
CREATE TRIGGER set_timestamp_financial_data BEFORE UPDATE ON public.financial_data
    FOR EACH ROW EXECUTE FUNCTION public.trigger_set_timestamp();
