# fly.toml app configuration file generated for seemycity-frontend on 2025-04-08T20:40:36+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'seemycity-frontend'
primary_region = 'jnb'

# Use the default build section, Fly will use the Dockerfile
[build]

# Use http_service as the Dockerfile now runs Nginx on port 80
[http_service]
  internal_port = 80 # Nginx default port
  force_https = true
  auto_stop_machines = false # Stop machines when idle
  auto_start_machines = true # Start machines on new requests
  min_machines_running = 1 # Allow scaling to zero
  processes = ["app"] # Matches the default process group

# Keep the vm section for defining machine resources
[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
